staffchat:
  error: "§cYou are not allowed to execute this command. Contact a server administrator if you believe this is an error."
  toggle-on: "§3You have toggled staff chat §aon§3!"
  toggle-off: "§3You have toggled staff chat §coff§3!"
  header: "§e§lStaffChat§7§l》"