name: StaffChat
main: dev.pace.staffchat.StaffChat
version: 2.0
author: Pace
api-version: 1.13
softdepend: [PlaceholderAPI]
commands:
  staffchat:
    description: Staff chat command.
  sc:
    description: Staff chat command.
  sctoggle:
    description: Toggle messages from staff chat.
    aliases:
      - staffchattoggle
  screload:
    description: Reloads config.
  adminchat:
    description: Admin chat command.
    aliases:
      - asc
      - adminstaffchat
      - ac
  adminchattoggle:
    description: Toggle messages from admin chat.
    aliases:
      - actoggle
  schelp:
    description: Shows all staff chat commands.
    aliases:
      - staffchathelp
  devchat:
    description: Developer chat command.
    aliases:
      - developerchat
      - dc
  devchattoggle:
    description: Toggle messages from Developer chat.
    aliases:
      - developerchattoggle