name: StaffChat
version: ${project.version}
main: dev.pace.staffchat.Main
api-version: 1.13
commands:
  staffchat:
    description: Staff chat command.
  sc:
    description: Staff chat command.
  sctoggle:
    description: Toggle messages from staff chat.
    aliases:
      - staffchattoggle
  screload:
    description: Reloads config.
  adminchat:
    description: Admin chat command.
    aliases:
      - ac
  adminchattoggle:
    description: Toggle messages from admin chat.
    aliases:
      - actoggle